
services:
  # Serviço Backend
  backend:
    build:
      context: .
    container_name: capitech-backend
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - DB_PATH=mongodb://mongodb:27017/Capitech
      - JWT_SECRET=qJSBO1GY036KAJV4hvtc1Gt0yBQ
      - ADMIN_CODE=Fatec2024Votorantim

  # Serviço Frontend
  frontend:
    build:
      context: ../Capitech-front
    container_name: capitech-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_SERVICE_ID="service_plrbyoy"
      - NEXT_PUBLIC_TEMPLATE_ID="template_mycbjog"
      - NEXT_PUBLIC_PUBLIC_KEY="BB1sMRYW_bq9hq4fM"
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=testeeeee
      - NEXT_PUBLIC_API_URL=http://backend:4000

  # Serviço MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db

volumes:
  mongodb_data: